import { addIcons } from 'ionicons';
import {
    personOutline,
    calendarOutline,
    peopleOutline,
    chevronDownOutline,
    callOutline,
    mailOutline,
    locationOutline,
    businessOutline,
    mapOutline,
    mailUnreadOutline,
    homeOutline,
    cardOutline,
    fingerPrintOutline,
    medicalOutline,
    checkmarkCircleOutline,
    syncOutline,
    refreshOutline,
    idCardOutline,
    cellular,
    menu,
    refresh,
    play,
    chevronBack,
    chevronForward,
    send,
    call,
    mail,
    logoFacebook,
    logoTwitter,
    logoInstagram,
    logoLinkedin,
    star,
    wifi,
    tv,
    card,
    cloud,
    headset,
    flash,
    shieldCheckmark,
    people,
    trendingUp
} from 'ionicons/icons';

export function configureIonicons(): void {
    addIcons({
        'sim-outline': idCardOutline,
        'person-outline': personOutline,
        'calendar-outline': calendarOutline,
        'people-outline': peopleOutline,
        'chevron-down-outline': chevronDownOutline,
        'call-outline': callOutline,
        'mail-outline': mailOutline,
        'location-outline': locationOutline,
        'business-outline': businessOutline,
        'map-outline': mapOutline,
        'mail-unread-outline': mailUnreadOutline,
        'home-outline': homeOutline,
        'card-outline': cardOutline,
        'finger-print-outline': fingerPrintOutline,
        'medical-outline': medicalOutline,
        'checkmark-circle-outline': checkmarkCircleOutline,
        'sync-outline': syncOutline,
        'refresh-outline': refreshOutline,
        'cellular': cellular,
        'menu': menu,
        'refresh': refresh,
        'play': play,
        'chevron-back': chevronBack,
        'chevron-forward': chevronForward,
        'send': send,
        'call': call,
        'mail': mail,
        'logo-facebook': logoFacebook,
        'logo-twitter': logoTwitter,
        'logo-instagram': logoInstagram,
        'logo-linkedin': logoLinkedin,
        'star': star,
        'wifi': wifi,
        'tv': tv,
        'card': card,
        'cloud': cloud,
        'headset': headset,
        'flash': flash,
        'shield-checkmark': shieldCheckmark,
        'people': people,
        'trending-up': trendingUp
    });
}